version: '3.4'

services:
  steamcmdunturned:
    image: yourDockerHub/image
    container_name: unturnedServer
    ports:
    - 27015:27015
    - 27015:27015/udp
    - 27016:27016
    - 27016:27016/udp
    std_open: true
    tty: true
    environment:
      UID: 1026
      GID: 100
    volumes:
      - /volume1/docker/unturnedServer:/serverFiles
    restart: "no"